---
title: "Materials"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Have you used our book? We want to hear from you!

Please e-mail Sara Stoudt (sas072@bucknell.edu)

## Teaching Materials

### Original Class (that inspired the book)
Taught by Deborah Nolan and Sara Stoudt at UC Berkeley

[Syllabus](https://docs.google.com/document/d/1p_8K5FmxXuLoY1F-JNOZ7JqpencltEkc/edit?usp=sharing&ouid=113602332587941801594&rtpof=true&sd=true)

### First Year Seminar: Storytelling with Data
Taught by Sara Stoudt at Bucknell University

Day-to-day overview Fall '25: coming soon

[Day-to-day overview Fall '24](https://docs.google.com/document/d/1s5fMx7xj-GriTfHx2aZYVkkY-m99iS6-FEsTx8joExE/edit?usp=sharing)

[Day-to-day overview Fall '22](https://docs.google.com/document/d/19HnV9PRFGb4djHFBuL_dhYraV4fL9zRoGwPhQoE9BAs/edit?usp=sharing)



## More on Reading to Write

[Nolan, Deborah, and Sara Stoudt. "Reading to write." Significance 17.6 (2020).](https://academic.oup.com/jrssig/article/17/6/34/7037923)

## More on Storyboarding

**paper coming soon**

[Nolan, Deborah, and Sara Stoudt. "Storyboarding as Part of the Process of Statistical Investigation" USCOTS (2021)](https://www.causeweb.org/cause/uscots/uscots21/th-21-storyboarding-part-process-statistical-investigation)

## More on Presentations

[Stoudt, Sara. "Can TV make you a better stats communicator?." Significance (2023).](https://doi.org/10.1093/jrssig/qmad063)


## More on Revision

[Nolan, Deborah, and Sara Stoudt. "Revision Beyond the Copyedit: Encouraing Students to Reorganize, Restructure, and Refocus in Writing Assignments" ICOTS 11 (2022)](https://iase-web.org/icots/11/proceedings/pdfs/ICOTS11_344_STOUDT.pdf?1669865558)

## More on Captions

[Nolan, Deborah, and Sara Stoudt. "Captions: The Unsung Heroes of Data Communication" IASE (2021)](https://iase-web.org/documents/papers/sat2021/IASE2021%20Satellite%20174_STOUDT.pdf?1649974218)

## More on Portfolios

[Nolan, Deborah, and Sara Stoudt. "The promise of portfolios: Training modern data scientists." Harvard Data Science Review 3.3 (2021).](https://hdsr.mitpress.mit.edu/pub/pm67plq9/release/4)

## Errata - p.206 Chapter 8

A rapid test for HIV was developed for its sensitivity: the new test was shown to have sensitivity of 83%, compared to 60% for a commonly used test. This increased detection rate matters because those with false negative results (HIV-positive individuals whose disease goes undetected by a test) are likely not to return for further testing. The specificity of the rapid test is 97%. For example in a population of 692,000 with 12,000 HIV-positive, we expect $(0.83*12,000 =) 9,960$ HIV-positive people to test positive and $((1-0.97)*(692,000 - 12,000) =) 20,400$ HIV-negative people to test positive. That is, the test has a precision of only $(9,960/(20,400+9,960) =) 32.8\%$. However the rapid test can be immediately administered a second time for anyone with a positive result. With this two-step approach the precision increases to $((12,000/69,2000*0.83^2)/((12,000/69,2000*0.83^2) + (680,000/692,000*0.03^2)) =) 93.1\%$.
